name: Build bld_Reconciliation_tool EXE
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
 
    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install dependencies
      run: pip install pandas numpy openpyxl xlrd 
 
    - name: Build EXE
      run: pyinstaller --version-file version.txt --onefile Bank_Reconciliation_Tool.py
      env:
        CC: mingw32-gcc
 
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: mgs_boc_recon
        path: dist/Bank_Reconciliation_Tool.exe
   
    - name: Get artifact download URL
      id: get-url
      run: |
        ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq '.artifacts[] | select(.name=="test-artifact") | .id')
        
        echo "Artifact ID: $ARTIFACT_ID"
        
        DOWNLOAD_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip"
        echo "::set-output name=download_url::$DOWNLOAD_URL"

    - name: Send URL to Bark
      run: |
        BARK_URL="https://api.day.app/YvFVCKrbcd5u5R3RWnJ8h7/${{ steps.get-url.outputs.download_url }}?copy=test"
        curl -X GET "$BARK_URL"
